services:
  proxy:
    image: ineva/dns-sd-proxy:1.0
    restart: unless-stopped
    environment:
      - SD_PROXY_NAME=NevaNAS
      - SD_PROXY_SERVICE=_smb._tcp
      - SD_PROXY_IP=192.168.1.3
      - SD_PROXY_PORT=445
      # - SD_PROXY_DOMAIN=local.
      # - SD_PROXY_HOST=pc1
    network_mode: host
